server:
  port: 8888

spring:
  application:
    name: cloud-config-service
  cloud:
    config:
      server: 
        git: 
          uri: https://github.com/SubprojectNhom03KTTKPM14/cloud-config
          default-label: main
